### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by SaMochaxD** [MicrosoftStudentChapter/mlsctiet#11]

**Comment by VishistB** [comment]
I would like to take this up

**Comment by arorasukhmani** [comment]
Functionality:
Built a carousel for every year's gallery component.
The main gallery page contains a scattered effect.
A grid with a backend has to be added.
Issues faced:
Different animations in the carousel for back and forth animations.
Scope of improvement:
Uniformity in animations.
Responsiveness of scattered effect.
