### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by SaMochaxD** [MicrosoftStudentChapter/mlsctiet#13]

**Comment by pkkaur13** [comment]
i can do this

**Comment by JhndaCoder** [comment]
Page status: 
> 1st part is completely ready and functional with animations and effects (The carousels are empty and will be filled with projects with time)
> Libraries used: react-reveal and swiperJS
> the 2nd part will be replaced with a coming soon page instead of the Loki sample
> issues faced: lack of teammates who could work on react or were familiar with media queries
> scope of improvement : The 1st page is good to go , the 2nd page could be done better
