### ISSUE TITLE
Issue with redirect when submitting contact form in the sponsers page

### ISSUE THREAD

**Issue by utkarsh-1905** [MicrosoftStudentChapter/mlsctiet#77]
<img width="281" alt="image" src="https://github.com/MicrosoftStudentChapter/mlsctiet/assets/83540694/9499039d-fc42-4159-ac3c-1c68e3b8b972">

## Steps to reproduce the issue
* Go to the sponsor page
* Fill out the reach-out form
* Click submit

Possible Issues
* Deprecation of web3api
* Incorrect redirect URI
* Incorrect implementation of the api

**Comment by MankiratSingh1315** [comment]
I want to work on this issue.

**Comment by utkarsh-1905** [comment]
#80 fixed this issue, kudos to @MankiratSingh1315
