### ISSUE TITLE
Gallery page

### ISSUE THREAD

**Issue by nimishmedatwal** [MicrosoftStudentChapter/mlsctiet#81]
Here's the [ figma link](https://www.figma.com/file/b6redbrOJoJDjWDjf7GMPA/MLSC-Website?type=design&node-id=437-39&mode=design&t=aojOIHlpH06IkZZy-0)

**Comment by adityacodes30** [comment]
Hi , i would like to work on this one

**Comment by UPSAtwal** [comment]
I am currently working on the gallery page

**Comment by arnavXgupta** [comment]
I would like to work on this page

**Comment by daanishmittal24** [comment]
Want to work on this page

**Comment by rohitarora156** [comment]
Would like to work on this page
