### ISSUE TITLE
Sponsers Page

### ISSUE THREAD

**Issue by nimishmedatwal** [MicrosoftStudentChapter/mlsctiet#82]
Here's the [ figma link](https://www.figma.com/file/b6redbrOJoJDjWDjf7GMPA/MLSC-Website?type=design&node-id=437-39&mode=design&t=aojOIHlpH06IkZZy-0)

**Comment by pk2409** [comment]
i am interested in working on this :)

**Comment by Siddharth-Agg-arwal** [comment]
I would like to contribute to this page

**Comment by sarthaksri** [comment]
I would also like to work on this!!

**Comment by SkaiLord** [comment]
Interested!

**Comment by MankiratSingh1315** [comment]
I am interested!

**Comment by vigkrishna** [comment]
Interested to contribute!!

**Comment by Krishnam2004** [comment]
Would love to contribute, was a part of the designing of new sponsors page.

**Comment by Dev22mehta17** [comment]
interested!!  (also was the part of designing this page )

**Comment by nimishmedatwal** [comment]
@vigkrishna and @MankiratSingh1315 this page is already assigned to 4 people you can work on the gallery page or the home page

**Comment by Aryan1mishra** [comment]
Intrested!!!
