### ISSUE TITLE
Alumni 

### ISSUE THREAD

**Issue by nimishmedatwal** [MicrosoftStudentChapter/mlsctiet#83]
Here's the [ figma link](https://www.figma.com/file/b6redbrOJoJDjWDjf7GMPA/MLSC-Website?type=design&node-id=437-39&mode=design&t=aojOIHlpH06IkZZy-0)

**Comment by ShreyaA3108** [comment]
I would like to work on this!

**Comment by Winniper** [comment]
I am interested to work on this page :)

**Comment by Lishika3009** [comment]
I would like to work on this page.

**Comment by RijulBansal** [comment]
I am interested to work on this page!

**Comment by daanishmittal24** [comment]
will also work on this page

**Comment by Yuvrajg2442** [comment]
I would like to work on this page.

**Comment by Prekshaa21** [comment]
I'd like t work on this page.

**Comment by parusha9** [comment]
I would like to work on this page

**Comment by k-gos** [comment]
I would like to work on this.

**Comment by akshitak21** [comment]
I would like to work on this page
