### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by nimishmedatwal** [MicrosoftStudentChapter/mlsctiet#84]
Here's the [ figma link](https://www.figma.com/file/b6redbrOJoJDjWDjf7GMPA/MLSC-Website?type=design&node-id=437-39&mode=design&t=aojOIHlpH06IkZZy-0)

**Comment by Palak05Kaur** [comment]
I am up to work for home page!!!!

**Comment by jay-lak** [comment]
I want to work on this.

**Comment by MankiratSingh1315** [comment]
I am interested to work on this page

**Comment by AnushkaPhogat16** [comment]
I'd like to work on this page

**Comment by dgbkn** [comment]
i would like to work on this and add three.js 's animations to MLSC logo.
