### ISSUE TITLE
Alumni

### ISSUE THREAD

**Issue by SaMochaxD** [MicrosoftStudentChapter/mlsctiet#9]

**Comment by Yashvi30** [comment]
![WhatsApp Image 2022-06-18 at 4 10 31 PM](https://user-images.githubusercontent.com/65728655/174492016-fe05777c-6ec4-40d7-8620-50c637535763.jpeg)
![WhatsApp Image 2022-06-18 at 4 10 43 PM](https://user-images.githubusercontent.com/65728655/174492021-790033b8-90c9-484b-a8fb-bc7b53046d4c.jpeg)

I want to take up this issue
